# 事前準備(Windows編)

それでは，早速お手持ちのWindowsパソコンにDockerを導入しましょう（Macは次の[「4 事前準備（Mac編）」](https://ykunisato.github.io/jpa2020-tws-002/04.html)をご覧ください）。なお，　Dockerを使うにあたって，15GBくらいハードディスクに余裕があると良いかと思います。


## Windows10のエディションを確認する（ProかHomeか）

多くの方が，Windows10をお使いだとは思いますが，一般的に使われるWindowsにはProとHomeの２つのエディションがあります。エディションによってDockerの導入方法が異なります。以下の解説動画で，ご自身のパソコンのWindowsがProかHomeのどちらかをご確認ください。

<iframe width="560" height="315" src="https://www.youtube.com/embed/qw5iVL8Zhek" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br />

## Windows10がProエディションの場合の導入方法

Windows10 Proエディションの方は以下の動画を参考にDockerを導入なさってください。なお，コマンドプロンプトに打ち込むコードについて，動画内で紹介しているものでも動きますが，以下で書いているコードのほうが楽だし上手くいくと思います。

<iframe width="560" height="315" src="https://www.youtube.com/embed/aStsqv2DpF4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

コマンドプロンプトに打ち込むDocker用のコードは以下になります。**以下のコードは動画内で口頭で解説しているものとは異なりますが，こちらのほうが簡単かつ上手くいくと思います！（-e DISABLE_AUTH=trueは便利ですが，複数アカウントがある場合は挙動がつかめないのでおすすめしないです））**ローカルで，ご自身が所有しているパソコンでの利用を想定しているのでパスワードはpaperに固定しています（気になる場合は改変ください）。

```
docker run -e PASSWORD=paper -p 8787:8787 -v "%cd%":/home/rstudio -d --name paper ykunisato/paper-r
```

終わったら，ブラウザのアドレスバーに**localhost:8787**と打ち込んで，出てきたログイン画面のUsernameに**rstudio**, Passwordに**paper**(もしくはご自身で設定したパスワード)をいれてください。普段使っているホームディレクトリがマウントされていると思います。

<br />

## Windows10がHomeエディションの場合の導入方法

Windows10 Homeエディションの方は以下の動画を参考にDockerを導入なさってください。なお，コマンドプロンプトに打ち込むコードについて，動画内で紹介しているものでも動きますが，以下で書いているコードのほうが楽だし上手くいくと思います。

<iframe width="560" height="315" src="https://www.youtube.com/embed/wLEZcc4erlc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

コマンドプロンプトに打ち込むDocker用のコードは以下になります。**以下のコードは動画内で口頭で解説しているものとは異なりますが，こちらのほうが簡単かつ上手くいくと思います！（-e DISABLE_AUTH=trueは便利ですが，複数アカウントがある場合は挙動がつかめないのでおすすめしないです））**ローカルで，ご自身が所有しているパソコンでの利用を想定しているのでパスワードはpaperに固定しています（気になる場合は改変ください）。

```
docker run -e PASSWORD=paper -p 8787:8787 -v "%cd%":/home/rstudio -d --name paper ykunisato/paper-r
```

終わったら，ブラウザのアドレスバーに**localhost:8787**と打ち込んで，出てきたログイン画面のUsernameに**rstudio**, Passwordに**paper**(もしくはご自身で設定したパスワード)をいれてください。普段使っているホームディレクトリがマウントされていると思います。

<br />

## Dockerコマンド

### コンテナの確認と開始

コンテナの動作確認するには，コマンドプロンプトに以下を打ち込みます。STATUSがUpになっているとコンテナが動いています（再起動後に止まったりしていることがある）。

```
docker ps -a
```

もしコンテナが停止している場合は(STATUSがExitedになっている)，コマンドプロンプトに以下を打ち込んで，コンテナを開始します。

```
docker start コンテナ名(上記の場合はpaper)
```

### コンテナの停止と削除，イメージの削除

もうコンテナが不要になったら，停止して削除します。コンテナの停止には，コマンドプロンプトに以下を打ち込みます。

```
docker stop コンテナ名(上記の場合はpaper)
```

コンテナの削除には，コマンドプロンプトに以下を打ち込みます。

```
docker rm コンテナ名(上記の場合はpaper)
```

rmしてもコンテナが削除されただけでダウンロードしたイメージは残っています。まず，以下をコマンドプロンプトに打ち込んで，イメージの状況を確認します。削除したいイメージのIMAGE IDをコピーします。

```
docker images
```

上記でコピーしたIMAGE IDを使って，以下をコマンドプロンプトに打ち込んで，イメージを削除します。

```
docker rmi IMAGE_ID
```

## Dockerが使えない場合

以下のソフトとパッケージをインストールください。

- R(https://www.r-project.org/)
- Rstudio(https://rstudio.com/)
- 私が用意したDockerイメージ内には大量のRパッケージがはいっているので，それと同じものを用意するのは難しいかと思います。とりあえず，デモコードを実施した場合にインストールするか聞かれるので，その都度インストールください。
