--- 
title: "再現可能な日本語論文執筆入門:jpaRmdで実現する再現可能で低コストな日本語論文執筆のはじめの一歩"
author: "国里愛彦(専修大学)・小杉 考司(専修大学)"
date: "2021/9/6(月) 9:30-11:30"
site: bookdown::bookdown_site
output:
  bookdown::html_book
documentclass: book
---

# はじめに

本サイトは，日本心理学会第84回大会(以下，JPA2020)のチュートリアルワークショップ(以下，TWS)「再現可能な日本語論文執筆入門:jpaRmdで実現する再現可能で低コストな日本語論文執筆のはじめの一歩」の事前準備と当日(2021/9/6(月) 9:30-11:30)の演習用サイトになります。本サイトもRStudioとRMarkdown(Bookdown)を使って作成されています。左の目次をクリックして移動するか，＞をクリックして次のページに移動ください。

## 連絡先

本サイトの内容で不明な点がございましたら，[メールフォーム](https://docs.google.com/forms/d/e/1FAIpQLSeVb0_ti9flHyGcRQcLESQO7Tzl3eH5hbCqXyzcGh7RWLQexA/viewform)からご連絡をいただけましたら幸いです。

## TWS概要

TWSの概要は以下になります。

> 再現可能性を高める上では，データから論文までをシームレスに接続して研究を行うことが推奨される。それによって，データの前処理から統計解析への移行時のミス，解析結果を論文内に記載する際のミスを防ぐことができ，研究の再現可能性を高めることができる。これを可能にするソフトウェアとしてR  Markdownがあり，主要な学術雑誌のテンプレートが用意されている。国際誌の場合は既存のテンプレートを活用して論文執筆ができるが，国内誌の場合は日本語の処理や引用文献処理の問題もあり，適切なテンプレートが存在しない。そこで，我々は『心理学研究』などの国内誌に対応したjpaRmdパッケージを開発した。jpaRmdパッケージを使うことで，データの前処理，統計解析，論文執筆を１つのソフトウェア内でシームレスに扱うことができる。また，jpaRmdは投稿規定に沿った出力ができるので，フォーマット調整にかける労力を減らし，論文執筆に注力できる。本チュートリアルでは，各種ソフトウェアの導入からスタートし，再現性を高めるフォルダ構造の設定，そして実際にjpaRmdを使って論文執筆ができるようになることを目指す。